<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_About the University</name>
   <tag></tag>
   <elementGuidId>0bbaa5c5-b3cd-41ab-9142-87b02a8a981e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li > ul > li > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='mainav']/ul/li/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;About the University&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ef9a35f0-861d-4a7d-a208-86323525bac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>//www.bdu.ac.in/about/about-the-university.php</value>
      <webElementGuid>7705c9f0-c9b1-4ef4-aeb1-7f5564da6ba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>About the University</value>
      <webElementGuid>255d40d5-187d-4847-8705-06db11a2987d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainav&quot;)/ul[@class=&quot;clear&quot;]/li[1]/ul[1]/li[1]/a[1]</value>
      <webElementGuid>607ba705-d3c7-4e05-853c-d75be3dbe0b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='mainav']/ul/li/ul/li/a</value>
      <webElementGuid>ac3548f1-f01e-421b-87da-71cb7d47514b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'About the University')]</value>
      <webElementGuid>1b3ab19e-c9b2-4c1e-be12-48afbb9514c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BDU Univ. Depts - Admissions (2024-2025)'])[1]/following::a[3]</value>
      <webElementGuid>6aea56fb-39eb-489f-9021-43a92d82769f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='University Act'])[1]/preceding::a[1]</value>
      <webElementGuid>fb3d6362-1b19-4f8e-b159-05d17f0eb985</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Statutes'])[1]/preceding::a[2]</value>
      <webElementGuid>8a5b3b6f-cb72-424d-9d75-ed67f87e2e8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='About the University']/parent::*</value>
      <webElementGuid>495d4bc9-f7e8-48f1-bc65-c0b454642595</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '//www.bdu.ac.in/about/about-the-university.php')]</value>
      <webElementGuid>44b9e8bf-4274-492d-9221-03ec11787efa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li/a</value>
      <webElementGuid>1afb06df-d6f3-4a59-aec9-2b91316c4431</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '//www.bdu.ac.in/about/about-the-university.php' and (text() = 'About the University' or . = 'About the University')]</value>
      <webElementGuid>1cc8a03a-8b54-45b1-944b-9d8a8e723b74</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
