<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Statutes</name>
   <tag></tag>
   <elementGuidId>59b97529-626f-4635-ba12-7f85f6e74369</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li > ul > li:nth-of-type(3) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='mainav']/ul/li/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#mainav >> internal:role=link[name=&quot;Statutes&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b298e463-edc9-4bdb-8581-1d772863fec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>//www.bdu.ac.in/about/bdu-statutes.php</value>
      <webElementGuid>0b9cbbe8-3351-4ff8-b9b6-d03839740bc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Statutes</value>
      <webElementGuid>a031c730-a0a2-4e81-aef5-2b75b6c597f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainav&quot;)/ul[@class=&quot;clear&quot;]/li[1]/ul[1]/li[3]/a[1]</value>
      <webElementGuid>ae56c087-110e-4468-8275-4c30442c527d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='mainav']/ul/li/ul/li[3]/a</value>
      <webElementGuid>ccd999ef-edd8-4311-82a9-fb1443bd10eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Statutes')]</value>
      <webElementGuid>aee29512-56b7-40cb-85db-dad2d44bbf05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='University Act'])[1]/following::a[1]</value>
      <webElementGuid>4d7b159c-e7bd-4877-94a3-f07d2e92913f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About the University'])[1]/following::a[2]</value>
      <webElementGuid>c3a8f1bb-ddea-4d4b-8f11-9802a1b18946</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Core Values'])[1]/preceding::a[1]</value>
      <webElementGuid>e346ff6b-381a-4529-95dc-18447658f12d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Campuses'])[1]/preceding::a[2]</value>
      <webElementGuid>4285a632-5126-4ef5-bac6-50e9aa258b12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Statutes']/parent::*</value>
      <webElementGuid>826bd64e-b1a5-48fd-9a10-4e5ec9b23176</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '//www.bdu.ac.in/about/bdu-statutes.php')]</value>
      <webElementGuid>c586bb08-f1ba-49da-b07e-75ce8be89319</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li[3]/a</value>
      <webElementGuid>b252dd27-4997-4301-b554-d6374d65be79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '//www.bdu.ac.in/about/bdu-statutes.php' and (text() = 'Statutes' or . = 'Statutes')]</value>
      <webElementGuid>575b1e16-971b-4edb-817a-7a384bd056ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
